name: Convert and Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Jupyter
        run: pip install notebook

      - name: Convert notebook to HTML
        run: jupyter nbconvert --to html --output index.html Stephen_King_Timeline.ipynb

      - name: Commit generated HTML
        run: |
          git config user.name github-actions
          git config user.email actions@github.com
          git add index.html
          git commit -m "Auto-update index.html"
          git push
